name: dagger
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dagger:
    name: dagger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Function build with mvn
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: build-maven --source=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Call Dagger Function build with gradle
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: build-gradle --source=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
